### ISSUE TITLE
README.md is not a markdown file.

### ISSUE THREAD

**Issue by Balgardner** [luisbg/git-cheat-sheet#2]
Hi Luis - thanks for sharing the cheat-sheet - very handy.

Was about to copy/paste some of the tips into another document and noticed that the README.md file is actually an HTML file. Renders on a site like GitHub much like a markdown file ultimately would but not an '.md' file per-se, so misleadingly labelled. A small thing but stopped me taking advantage of the share. :(

**Comment by luisbg** [comment]
Hi @Balgardner 

I've created a git_cheat_sheet.md file that is markdown. Let me know if that is what you needed :)

Thanks for letting me know about this issue

**Comment by Balgardner** [comment]
That's really good of you and just what I was looking for - thanks very much. The collection of tips is nicely presented and described - thank you for taking the time to do this. :+1:

**Comment by luisbg** [comment]
Awesome :) Closing this issue. I'm glad you enjoy it.
